import { LoveType, MBTIType } from './types';

// 16가지 연애 유형 데이터
export const loveTypes: Record<MBTIType, LoveType> = {
    ENFP: {
        code: 'ENFP',
        title: '열정적인 영감가',
        nickname: '자유로운 연애인',
        description: '열정적이고 창의적인 연애를 추구하는 타입입니다. 새로운 경험과 자유를 중시하며, 연인과 함께 성장하는 것을 원합니다.',
        loveStyle: '열정적이고 자유로운 연애',
        strengths: ['창의적인 데이트 아이디어', '긍정적인 에너지', '연인의 꿈을 응원', '자유로운 관계'],
        challenges: ['일관성 부족', '계획성 부족', '감정 기복'],
        compatibleTypes: ['INTJ', 'INFJ', 'ENTJ'],
        incompatibleTypes: ['ISTJ', 'ISFJ'],
        advice: '연인과 함께 새로운 경험을 나누되, 약속은 꼭 지키도록 노력하세요.',
        color: 'from-pink-400 to-rose-500'
    },
    ENFJ: {
        code: 'ENFJ',
        title: '따뜻한 조력자',
        nickname: '완벽한 연인',
        description: '연인의 성장과 행복을 최우선으로 생각하는 타입입니다. 따뜻하고 배려심이 깊어 이상적인 연인으로 여겨집니다.',
        loveStyle: '따뜻하고 배려심 깊은 연애',
        strengths: ['완벽한 배려심', '연인 성장 도움', '조화로운 관계', '따뜻한 위로'],
        challenges: ['자기 희생 과다', '비판에 민감', '완벽주의'],
        compatibleTypes: ['INFP', 'ISFP', 'INTP'],
        incompatibleTypes: ['ISTP', 'ESTP'],
        advice: '연인을 위해 희생하는 것도 좋지만, 자신의 감정과 욕구도 소중히 여기세요.',
        color: 'from-rose-400 to-pink-500'
    },
    ENTP: {
        code: 'ENTP',
        title: '도전적인 토론가',
        nickname: '지적인 연애인',
        description: '지적 호기심이 많고 토론을 즐기는 타입입니다. 연인과의 지적 교감을 중시하며, 새로운 아이디어를 함께 탐구합니다.',
        loveStyle: '지적이고 도전적인 연애',
        strengths: ['풍부한 대화', '창의적 아이디어', '유연한 사고', '도전 정신'],
        challenges: ['일관성 부족', '감정 표현 어려움', '세부사항 무시'],
        compatibleTypes: ['INFJ', 'INTJ', 'INFP'],
        incompatibleTypes: ['ISFJ', 'ESFJ'],
        advice: '연인과의 지적 교감도 좋지만, 감정적 교감도 소중히 여기세요.',
        color: 'from-purple-400 to-indigo-500'
    },
    ENTJ: {
        code: 'ENTJ',
        title: '리더십 있는 지휘관',
        nickname: '목표지향적 연애인',
        description: '목표 지향적이고 리더십이 강한 타입입니다. 연인과 함께 미래를 계획하고 성공을 추구합니다.',
        loveStyle: '목표지향적이고 계획적인 연애',
        strengths: ['명확한 목표 설정', '리더십', '효율적인 계획', '성취욕'],
        challenges: ['감정 표현 부족', '유연성 부족', '지배욕'],
        compatibleTypes: ['INFP', 'INTP', 'ISFP'],
        incompatibleTypes: ['ISFP', 'ESFP'],
        advice: '목표 달성도 중요하지만, 연인과의 감정적 교감도 놓치지 마세요.',
        color: 'from-blue-500 to-indigo-600'
    },
    ESFP: {
        code: 'ESFP',
        title: '즐거운 연예인',
        nickname: '즐거운 연애인',
        description: '즐겁고 활발한 성격으로 연인과 함께 즐거운 시간을 보내는 것을 중시합니다. 자발적이고 열정적입니다.',
        loveStyle: '즐겁고 활발한 연애',
        strengths: ['긍정적 에너지', '즐거운 데이트', '자발적 표현', '유연한 성격'],
        challenges: ['계획성 부족', '갈등 회피', '장기적 관점 부족'],
        compatibleTypes: ['ISFJ', 'ISTJ', 'INTJ'],
        incompatibleTypes: ['INTP', 'INTJ'],
        advice: '즐거운 시간도 좋지만, 연인과의 진지한 대화도 필요합니다.',
        color: 'from-yellow-400 to-orange-500'
    },
    ESFJ: {
        code: 'ESFJ',
        title: '따뜻한 돌봄이',
        nickname: '배려심 깊은 연애인',
        description: '배려심이 깊고 전통적인 가치를 중시하는 타입입니다. 연인을 돌보고 안정적인 관계를 추구합니다.',
        loveStyle: '전통적이고 안정적인 연애',
        strengths: ['완벽한 배려', '안정적인 관계', '전통적 가치', '희생정신'],
        challenges: ['자기주장 부족', '변화 거부', '비판에 민감'],
        compatibleTypes: ['ISFP', 'ISTP', 'INFP'],
        incompatibleTypes: ['ENTP', 'INTP'],
        advice: '연인을 배려하는 것도 좋지만, 자신의 의견도 적극적으로 표현하세요.',
        color: 'from-green-400 to-emerald-500'
    },
    ESTP: {
        code: 'ESTP',
        title: '활동적인 모험가',
        nickname: '액션 연애인',
        description: '활동적이고 모험을 즐기는 타입입니다. 연인과 함께 새로운 경험과 스릴을 추구합니다.',
        loveStyle: '활동적이고 모험적인 연애',
        strengths: ['액티브한 데이트', '즉흥적 재미', '현실적 판단', '유연한 성격'],
        challenges: ['장기적 계획 부족', '감정 표현 어려움', '규칙 거부'],
        compatibleTypes: ['ISFJ', 'ISTJ', 'INFJ'],
        incompatibleTypes: ['INFP', 'ENFJ'],
        advice: '즐거운 모험도 좋지만, 연인과의 깊은 대화도 필요합니다.',
        color: 'from-red-400 to-pink-500'
    },
    ESTJ: {
        code: 'ESTJ',
        title: '책임감 있는 관리자',
        nickname: '신뢰할 수 있는 연애인',
        description: '책임감이 강하고 체계적인 타입입니다. 연인과의 관계에서도 안정성과 신뢰를 중시합니다.',
        loveStyle: '체계적이고 안정적인 연애',
        strengths: ['신뢰성', '체계적 계획', '책임감', '안정성'],
        challenges: ['유연성 부족', '감정 표현 어려움', '변화 거부'],
        compatibleTypes: ['ISFP', 'ISTP', 'INFP'],
        incompatibleTypes: ['INFP', 'ENFP'],
        advice: '체계적인 관계도 좋지만, 연인과의 감정적 교감도 중요합니다.',
        color: 'from-gray-500 to-slate-600'
    },
    INFP: {
        code: 'INFP',
        title: '이상주의적 중재자',
        nickname: '로맨틱한 연애인',
        description: '이상적이고 로맨틱한 연애를 추구하는 타입입니다. 깊은 정신적 교감과 진정한 사랑을 중시합니다.',
        loveStyle: '이상적이고 로맨틱한 연애',
        strengths: ['깊은 감정', '이상적 사랑', '창의적 표현', '진정성'],
        challenges: ['현실성 부족', '갈등 회피', '완벽주의'],
        compatibleTypes: ['ENFJ', 'ENTJ', 'INFJ'],
        incompatibleTypes: ['ESTJ', 'ISTJ'],
        advice: '이상적인 사랑도 좋지만, 현실적인 부분도 고려하세요.',
        color: 'from-purple-300 to-pink-400'
    },
    INFJ: {
        code: 'INFJ',
        title: '통찰력 있는 옹호자',
        nickname: '신비로운 연애인',
        description: '깊은 통찰력과 직감을 가진 타입입니다. 연인과의 깊은 정신적 교감과 이해를 중시합니다.',
        loveStyle: '깊고 신비로운 연애',
        strengths: ['깊은 이해', '직감적 판단', '이상적 관계', '신비로운 매력'],
        challenges: ['완벽주의', '갈등 회피', '현실성 부족'],
        compatibleTypes: ['ENFP', 'ENTP', 'INFP'],
        incompatibleTypes: ['ESTP', 'ESFP'],
        advice: '깊은 교감도 좋지만, 연인과의 소통도 적극적으로 하세요.',
        color: 'from-indigo-400 to-purple-500'
    },
    INTP: {
        code: 'INTP',
        title: '논리적인 사색가',
        nickname: '지적인 연애인',
        description: '논리적이고 분석적인 사고를 가진 타입입니다. 연인과의 지적 교감과 독립성을 중시합니다.',
        loveStyle: '지적이고 독립적인 연애',
        strengths: ['논리적 사고', '독립성', '지적 호기심', '객관적 판단'],
        challenges: ['감정 표현 어려움', '소통 부족', '현실성 부족'],
        compatibleTypes: ['ENTJ', 'ESTJ', 'INFJ'],
        incompatibleTypes: ['ESFP', 'ESFJ'],
        advice: '지적 교감도 좋지만, 연인과의 감정적 소통도 필요합니다.',
        color: 'from-blue-400 to-cyan-500'
    },
    INTJ: {
        code: 'INTJ',
        title: '전략적인 건축가',
        nickname: '계획적인 연애인',
        description: '전략적이고 장기적인 관점을 가진 타입입니다. 연인과의 관계에서도 체계적이고 목표지향적입니다.',
        loveStyle: '전략적이고 장기적인 연애',
        strengths: ['장기적 계획', '논리적 판단', '독립성', '목표 지향'],
        challenges: ['감정 표현 어려움', '유연성 부족', '소통 부족'],
        compatibleTypes: ['ENFP', 'ENTP', 'INFP'],
        incompatibleTypes: ['ESFP', 'ESFJ'],
        advice: '체계적인 관계도 좋지만, 연인과의 감정적 교감도 중요합니다.',
        color: 'from-slate-600 to-gray-700'
    },
    ISFP: {
        code: 'ISFP',
        title: '유연한 예술가',
        nickname: '감성적인 연애인',
        description: '감성적이고 예술적인 감각을 가진 타입입니다. 연인과의 조화로운 관계와 개인의 자유를 중시합니다.',
        loveStyle: '감성적이고 조화로운 연애',
        strengths: ['감성적 표현', '예술적 감각', '조화로운 관계', '개인적 자유'],
        challenges: ['갈등 회피', '자기주장 부족', '계획성 부족'],
        compatibleTypes: ['ESFJ', 'ESTJ', 'ENFJ'],
        incompatibleTypes: ['ENTJ', 'ESTP'],
        advice: '조화로운 관계도 좋지만, 자신의 의견도 적극적으로 표현하세요.',
        color: 'from-pink-300 to-rose-400'
    },
    ISFJ: {
        code: 'ISFJ',
        title: '따뜻한 수호자',
        nickname: '보호자 연애인',
        description: '따뜻하고 보호적인 성격을 가진 타입입니다. 연인을 돌보고 안정적인 관계를 추구합니다.',
        loveStyle: '보호적이고 안정적인 연애',
        strengths: ['완벽한 보호', '안정적 관계', '희생정신', '전통적 가치'],
        challenges: ['자기주장 부족', '변화 거부', '완벽주의'],
        compatibleTypes: ['ESFP', 'ESTP', 'ENFP'],
        incompatibleTypes: ['ENTP', 'INTP'],
        advice: '연인을 보호하는 것도 좋지만, 자신의 욕구도 소중히 여기세요.',
        color: 'from-emerald-400 to-teal-500'
    },
    ISTP: {
        code: 'ISTP',
        title: '실용적인 장인',
        nickname: '실용적 연애인',
        description: '실용적이고 현실적인 타입입니다. 연인과의 관계에서도 실용성과 개인의 공간을 중시합니다.',
        loveStyle: '실용적이고 독립적인 연애',
        strengths: ['실용적 도움', '독립성', '현실적 판단', '유연한 성격'],
        challenges: ['감정 표현 어려움', '소통 부족', '계획성 부족'],
        compatibleTypes: ['ESTJ', 'ESFJ', 'ENTJ'],
        incompatibleTypes: ['ENFJ', 'INFJ'],
        advice: '실용적인 도움도 좋지만, 연인과의 감정적 소통도 필요합니다.',
        color: 'from-orange-400 to-red-500'
    },
    ISTJ: {
        code: 'ISTJ',
        title: '신뢰할 수 있는 논리주의자',
        nickname: '신뢰할 수 있는 연애인',
        description: '신뢰할 수 있고 책임감이 강한 타입입니다. 연인과의 관계에서도 안정성과 신뢰를 최우선으로 합니다.',
        loveStyle: '신뢰할 수 있고 안정적인 연애',
        strengths: ['완벽한 신뢰성', '안정적 관계', '책임감', '체계적 계획'],
        challenges: ['유연성 부족', '감정 표현 어려움', '변화 거부'],
        compatibleTypes: ['ESFP', 'ESTP', 'ENFP'],
        incompatibleTypes: ['ENFP', 'INFP'],
        advice: '안정적인 관계도 좋지만, 연인과의 감정적 교감도 중요합니다.',
        color: 'from-gray-600 to-slate-700'
    }
};
