import { LoveType, MBTIType } from './useTest';

// 16가지 새로운 연애 유형 데이터 (L/F, C/A, R/P, O/E)
export const newLoveTypes: Record<MBTIType, LoveType> = {
  LCAO: {
    code: 'LCAO',
    title: '리더십 있는 애정표현가',
    nickname: '적극적 로맨틱',
    description: '연애에서 주도권을 잡고 적극적으로 애정을 표현하는 타입입니다. 현실적이면서도 낙관적인 성향을 가지고 있습니다.',
    loveStyle: '주도적이고 애정표현이 풍부한 연애',
    strengths: ['적극적인 리더십', '풍부한 애정표현', '현실적 판단', '낙관적 성격'],
    challenges: ['지나친 주도권', '감정 기복', '현실성 부족'],
    compatibleTypes: ['FFAP', 'FFRP', 'FCAO'],
    incompatibleTypes: ['LFRO', 'FFRO'],
    advice: '연인을 이끌되, 상대방의 의견도 충분히 들어주세요.',
    color: 'from-pink-400 to-rose-500'
  },
  LCAP: {
    code: 'LCAP',
    title: '열정적인 리더',
    nickname: '열정적 주도자',
    description: '연애에서 주도권을 잡고 열정적으로 애정을 표현하는 타입입니다. 감정적이고 열정적인 연애를 추구합니다.',
    loveStyle: '열정적이고 주도적인 연애',
    strengths: ['강한 리더십', '열정적 애정표현', '감정적 교감', '적극적 태도'],
    challenges: ['감정 기복', '지나친 열정', '현실성 부족'],
    compatibleTypes: ['FFAP', 'FCRP', 'LCRO'],
    incompatibleTypes: ['LFRO', 'FFRO'],
    advice: '열정도 좋지만, 연인의 감정도 고려하여 균형을 맞추세요.',
    color: 'from-red-400 to-pink-500'
  },
  LCRO: {
    code: 'LCRO',
    title: '현실적 애정표현가',
    nickname: '현실적 로맨틱',
    description: '연애에서 주도권을 잡고 현실적으로 애정을 표현하는 타입입니다. 낙관적이면서도 현실적인 연애를 추구합니다.',
    loveStyle: '현실적이고 주도적인 연애',
    strengths: ['현실적 리더십', '안정적 애정표현', '낙관적 성격', '체계적 계획'],
    challenges: ['감정 표현 부족', '지나친 현실성', '유연성 부족'],
    compatibleTypes: ['FFRO', 'FCAO', 'LCAO'],
    incompatibleTypes: ['LFAP', 'FFAP'],
    advice: '현실적인 계획도 좋지만, 연인과의 감정적 교감도 중요합니다.',
    color: 'from-blue-400 to-indigo-500'
  },
  LCRP: {
    code: 'LCRP',
    title: '열정적 현실주의자',
    nickname: '열정적 계획가',
    description: '연애에서 주도권을 잡고 현실적으로 애정을 표현하는 타입입니다. 열정적이면서도 현실적인 연애를 추구합니다.',
    loveStyle: '열정적이고 현실적인 연애',
    strengths: ['강한 리더십', '현실적 애정표현', '열정적 태도', '체계적 계획'],
    challenges: ['감정 기복', '지나친 완벽주의', '유연성 부족'],
    compatibleTypes: ['FFRP', 'FCRP', 'LCAP'],
    incompatibleTypes: ['LFAP', 'FFAP'],
    advice: '완벽한 계획도 좋지만, 연인과의 자발적인 순간도 소중히 여기세요.',
    color: 'from-purple-400 to-indigo-500'
  },
  LFAO: {
    code: 'LFAO',
    title: '수용적 리더',
    nickname: '배려심 깊은 주도자',
    description: '연애에서 주도권을 잡지만 상대방을 수용하는 타입입니다. 낙관적이면서도 배려심이 깊습니다.',
    loveStyle: '배려심 깊고 주도적인 연애',
    strengths: ['배려심 깊은 리더십', '수용적 태도', '낙관적 성격', '안정적 관계'],
    challenges: ['자기주장 부족', '지나친 배려', '결정력 부족'],
    compatibleTypes: ['FFAO', 'FCAO', 'LCAO'],
    incompatibleTypes: ['LFAP', 'FFAP'],
    advice: '상대방을 배려하는 것도 좋지만, 자신의 의견도 적극적으로 표현하세요.',
    color: 'from-green-400 to-emerald-500'
  },
  LFAP: {
    code: 'LFAP',
    title: '열정적 수용자',
    nickname: '열정적 배려자',
    description: '연애에서 주도권을 잡지만 상대방을 수용하는 타입입니다. 열정적이면서도 배려심이 깊습니다.',
    loveStyle: '열정적이고 배려심 깊은 연애',
    strengths: ['열정적 리더십', '수용적 태도', '감정적 교감', '배려심'],
    challenges: ['감정 기복', '자기주장 부족', '지나친 배려'],
    compatibleTypes: ['FFAP', 'FCAO', 'LFRO'],
    incompatibleTypes: ['LCAP', 'FFRP'],
    advice: '상대방을 배려하는 것도 좋지만, 자신의 감정도 솔직하게 표현하세요.',
    color: 'from-orange-400 to-red-500'
  },
  LFRO: {
    code: 'LFRO',
    title: '현실적 수용자',
    nickname: '현실적 배려자',
    description: '연애에서 주도권을 잡지만 상대방을 수용하는 타입입니다. 현실적이면서도 배려심이 깊습니다.',
    loveStyle: '현실적이고 배려심 깊은 연애',
    strengths: ['현실적 리더십', '수용적 태도', '안정적 관계', '체계적 계획'],
    challenges: ['감정 표현 부족', '자기주장 부족', '지나친 현실성'],
    compatibleTypes: ['FFRO', 'FCAO', 'LFAP'],
    incompatibleTypes: ['LCAP', 'FFAP'],
    advice: '현실적인 계획도 좋지만, 연인과의 감정적 교감도 필요합니다.',
    color: 'from-teal-400 to-cyan-500'
  },
  LFRP: {
    code: 'LFRP',
    title: '열정적 현실주의 수용자',
    nickname: '열정적 현실 배려자',
    description: '연애에서 주도권을 잡지만 상대방을 수용하는 타입입니다. 열정적이면서도 현실적이고 배려심이 깊습니다.',
    loveStyle: '열정적이고 현실적인 배려 연애',
    strengths: ['열정적 리더십', '수용적 태도', '현실적 판단', '배려심'],
    challenges: ['감정 기복', '자기주장 부족', '지나친 완벽주의'],
    compatibleTypes: ['FFRP', 'FCRP', 'LFAP'],
    incompatibleTypes: ['LCAP', 'FFAP'],
    advice: '완벽한 관계를 추구하는 것도 좋지만, 때로는 자연스러운 모습도 보여주세요.',
    color: 'from-indigo-400 to-purple-500'
  },
  FCAO: {
    code: 'FCAO',
    title: '따뜻한 팔로워',
    nickname: '애정표현 팔로워',
    description: '연애에서 상대방을 따라가며 애정을 표현하는 타입입니다. 낙관적이면서도 따뜻한 성향을 가지고 있습니다.',
    loveStyle: '따뜻하고 수용적인 연애',
    strengths: ['따뜻한 애정표현', '수용적 태도', '낙관적 성격', '조화로운 관계'],
    challenges: ['자기주장 부족', '지나친 수용', '결정력 부족'],
    compatibleTypes: ['LCAO', 'LFAP', 'FFAO'],
    incompatibleTypes: ['LCAP', 'FFRP'],
    advice: '상대방을 따라가는 것도 좋지만, 자신의 의견도 적극적으로 표현하세요.',
    color: 'from-pink-300 to-rose-400'
  },
  FCAP: {
    code: 'FCAP',
    title: '열정적 팔로워',
    nickname: '열정적 애정표현가',
    description: '연애에서 상대방을 따라가며 열정적으로 애정을 표현하는 타입입니다. 감정적이고 열정적인 연애를 추구합니다.',
    loveStyle: '열정적이고 수용적인 연애',
    strengths: ['열정적 애정표현', '수용적 태도', '감정적 교감', '따뜻한 마음'],
    challenges: ['감정 기복', '자기주장 부족', '지나친 열정'],
    compatibleTypes: ['LFAP', 'FFAP', 'FCRP'],
    incompatibleTypes: ['LCRO', 'FFRO'],
    advice: '열정적인 애정표현도 좋지만, 연인의 감정도 고려하여 균형을 맞추세요.',
    color: 'from-rose-400 to-pink-500'
  },
  FCRO: {
    code: 'FCRO',
    title: '현실적 팔로워',
    nickname: '현실적 애정표현가',
    description: '연애에서 상대방을 따라가며 현실적으로 애정을 표현하는 타입입니다. 낙관적이면서도 현실적인 연애를 추구합니다.',
    loveStyle: '현실적이고 수용적인 연애',
    strengths: ['현실적 애정표현', '수용적 태도', '안정적 관계', '체계적 계획'],
    challenges: ['감정 표현 부족', '자기주장 부족', '지나친 현실성'],
    compatibleTypes: ['LFRO', 'FFRO', 'FCAO'],
    incompatibleTypes: ['LCAP', 'FFAP'],
    advice: '현실적인 계획도 좋지만, 연인과의 감정적 교감도 필요합니다.',
    color: 'from-blue-300 to-indigo-400'
  },
  FCRP: {
    code: 'FCRP',
    title: '열정적 현실 팔로워',
    nickname: '열정적 현실주의자',
    description: '연애에서 상대방을 따라가며 현실적으로 애정을 표현하는 타입입니다. 열정적이면서도 현실적인 연애를 추구합니다.',
    loveStyle: '열정적이고 현실적인 수용 연애',
    strengths: ['열정적 애정표현', '현실적 판단', '수용적 태도', '체계적 계획'],
    challenges: ['감정 기복', '자기주장 부족', '지나친 완벽주의'],
    compatibleTypes: ['LFRP', 'FFRP', 'FCAP'],
    incompatibleTypes: ['LCAP', 'FFAP'],
    advice: '완벽한 관계를 추구하는 것도 좋지만, 때로는 자연스러운 모습도 보여주세요.',
    color: 'from-purple-300 to-indigo-400'
  },
  FFAO: {
    code: 'FFAO',
    title: '따뜻한 수용자',
    nickname: '배려심 깊은 팔로워',
    description: '연애에서 상대방을 따라가며 수용하는 타입입니다. 낙관적이면서도 배려심이 깊습니다.',
    loveStyle: '배려심 깊고 수용적인 연애',
    strengths: ['따뜻한 수용', '배려심', '낙관적 성격', '조화로운 관계'],
    challenges: ['자기주장 부족', '지나친 수용', '결정력 부족'],
    compatibleTypes: ['LFAO', 'FCAO', 'FFAP'],
    incompatibleTypes: ['LCAP', 'FFRP'],
    advice: '상대방을 배려하는 것도 좋지만, 자신의 의견도 적극적으로 표현하세요.',
    color: 'from-green-300 to-emerald-400'
  },
  FFAP: {
    code: 'FFAP',
    title: '열정적 수용자',
    nickname: '열정적 배려자',
    description: '연애에서 상대방을 따라가며 수용하는 타입입니다. 열정적이면서도 배려심이 깊습니다.',
    loveStyle: '열정적이고 배려심 깊은 수용 연애',
    strengths: ['열정적 수용', '배려심', '감정적 교감', '따뜻한 마음'],
    challenges: ['감정 기복', '자기주장 부족', '지나친 배려'],
    compatibleTypes: ['LFAP', 'FCAP', 'FFAO'],
    incompatibleTypes: ['LCRO', 'FFRO'],
    advice: '상대방을 배려하는 것도 좋지만, 자신의 감정도 솔직하게 표현하세요.',
    color: 'from-orange-300 to-red-400'
  },
  FFRO: {
    code: 'FFRO',
    title: '현실적 수용자',
    nickname: '현실적 배려자',
    description: '연애에서 상대방을 따라가며 수용하는 타입입니다. 현실적이면서도 배려심이 깊습니다.',
    loveStyle: '현실적이고 배려심 깊은 수용 연애',
    strengths: ['현실적 수용', '배려심', '안정적 관계', '체계적 계획'],
    challenges: ['감정 표현 부족', '자기주장 부족', '지나친 현실성'],
    compatibleTypes: ['LFRO', 'FCRO', 'FFAO'],
    incompatibleTypes: ['LCAP', 'FFAP'],
    advice: '현실적인 계획도 좋지만, 연인과의 감정적 교감도 필요합니다.',
    color: 'from-teal-300 to-cyan-400'
  },
  FFRP: {
    code: 'FFRP',
    title: '열정적 현실 수용자',
    nickname: '완벽한 배려자',
    description: '연애에서 상대방을 따라가며 수용하는 타입입니다. 열정적이면서도 현실적이고 배려심이 깊습니다.',
    loveStyle: '열정적이고 현실적인 완벽한 배려 연애',
    strengths: ['열정적 수용', '현실적 판단', '배려심', '체계적 계획'],
    challenges: ['감정 기복', '자기주장 부족', '지나친 완벽주의'],
    compatibleTypes: ['LFRP', 'FCRP', 'FFAP'],
    incompatibleTypes: ['LCAP', 'FFAO'],
    advice: '완벽한 관계를 추구하는 것도 좋지만, 때로는 자연스러운 모습도 보여주세요.',
    color: 'from-indigo-300 to-purple-400'
  }
};
